"""Prepare three small Grok code/review bundles; no model invocation here."""
from pathlib import Path
import datetime, hashlib, json, shutil, tempfile, uuid

HERE=Path(__file__).resolve().parent
STUDIO=HERE.parents[2]/'studio'
ZDOC=HERE.parents[1]
stamp=datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')
batch=Path(tempfile.gettempdir())/('hh3d-bundles-'+stamp)
batch.mkdir(exist_ok=False)
header='''Return ONE JSON object: {"files":[{"path":"relative/file","content":"FULL source text"}],"notes":"limitations"}. No Markdown. Supply complete executable code, not a description. You do not run code or write files; coordinator will materialize, inspect and test your returned source. Do not claim any commands or tests passed. No tools needed: all required input below. Do not create reports saying work was done instead of code. Use original source only. Keep implementation simple and correct; do not implement later GT WPs. Deliver within 5 minutes.\n'''
runner='''Implement GT01 evidence bootstrap as stdlib Python3.11 module studio/build/bootstrap/run_fixture.py plus studio/tests/bootstrap/test_run_fixture.py (unittest via importlib). Build a CLI requiring --studio-root, --godot-exe, --console-sha256, --gui-sha256, --expected-version, --run-id, --command-id, --output, --timeout-seconds(default30). Resolve/examine input paths before running, reject symlinks/reparse points anywhere in fixture closure, traversal and missing/digest mismatched files. Expected console filename Godot_v*_win64_console.exe paired with *_win64.exe. Verify exact hashes and expected --version output prefix with dot-boundary; console+GUI+lock+runner+fixture hashes recorded. Caller pins hashes (observed diagnostics, not publisher trust). Output directory must not exist and be outside studio; exclusively create it (reject duplicate before launch). Copy trusted fixture closure excluding .godot and pyc into output/'snapshot có dấu'/sample-game; no canonical project mutation. Freeze fixture hashes before/after copy and compare; require source hash unchanged after run. Preserve logs and report on every failure once output exists. Run console --headless --path snapshot --editor --quit (import), then --headless --path snapshot --script res://scripts/trace.gd only if trace.gd exists, else diagnostic --quit-after2. Use subprocess.Popen with file stdout/stderr (no pipes deadlock), subprocess wait timeout; kill exact child through retained handle on timeout, never kill by name. Record actual pid, host launch timestamp, argv, exit, timeout. On Windows for console child GUI companion, if leftover cannot independently prove descendants zero, explicit LEFTOVER_UNVERIFIED and result DIAGNOSTIC, not PASS. Do not claim full GT01 acceptance. Keep absent process inventory honest; do not fabricate empty []. Record schema/run/command IDs and source manifest, no recursive self-hash. Return status DIAGNOSTIC or GAP with reason; zero exit only if executed stages clean, still no acceptance. Expose small functions hash_file, checked_files, run_process so unit tests can test them with real short Python subprocess fixtures. Tests: digest mismatch before any subprocess (mock called false), version mismatch, duplicate output, traversal/symlink when supported, timeout returns actual nonzero process exit, stdout stderr captured, Unicode paths with spaces, source mutated while copy detected. No dependencies beyond stdlib, bounded tests total<20sec. Avoid extensive overengineering; clear comments and failures.''' 
fixture='''Return complete replacement files ONLY studio/fixtures/sample-game/project.godot, main.tscn, scripts/main.gd, scripts/trace.gd. Implement Godot4.7 typed GDScript original small 2D technical fixture. Root Control PROCESS_MODE_ALWAYS; create VBox Start/Quit buttons in _ready with keyboard focus; explicit phase MENU/PLAY/PAUSED/QUITTING. Start via real Button UI accept, game scene draws simple avatar square and prop; movement arrow keys updates position only in PLAY, pause Escape toggles and freezes body/tick, return resume, quit Q from any phase. Expose snapshot() dictionary phase/body_position/tick solely for readback. Print JSON transition readbacks. No member names colliding with built-in Control or Node properties (e.g. position, owner). typed arrays/Variant warnings avoided. Fixture trace script extends SceneTree, instantiate main.tscn, wait process frames, inject InputEventKey events through Input.parse_input_event, press+release Enter to activate focused Start Button, then Right hold/release to prove move, Escape pause, wait ticks and prove freeze, Escape resume, Q quit. Actual button/key handlers used; no direct signal emit or _on_start call. Record trace postconditions with JSON and exit nonzero on mismatch. Ensure enough await frames per UI transition before assertions, trace auto timeout<=10seconds, no infinite loops. Use separate injected-key helper with typed args (Key or int consistent Godot4) and await process_frame. Watch typing load as PackedScene, instantiate Control casting, get main snapshot using explicit Dictionary variable. Non-headless fixture remains usable manually; trace runs headless or windowed via --script and must end with actual quit action. Clear labels, instructions, focus and pause state visible. Do not add Blender or other paths. Minimal code ~180lines max across scripts; correct syntax more important than breadth. Current source is appended below.\n'''
for rel in ['project.godot','main.tscn','scripts/main.gd']:
    fixture+='\nINPUT '+rel+'\n'+(STUDIO/'fixtures/sample-game'/rel).read_text(encoding='utf-8')
game=(ZDOC/'8-9-hh-world-gameplay-viet-nam-plan.txt').read_text(encoding='utf-8')
start=game.index('Release profile `contracts/release-profile-v1.json`')
review='''You are reviewing a PLAN CONTRACT, not code implementation. Return JSON {"findings":[{"severity":"P1/P2/P3","quote":"exact input clause","problem":"specific defect","replacement":"concrete text","test":"acceptance validation"}],"notes":"limits"}. No source files, no writes, no fabricated commands. Focus only release-profile signature and source manifest hash cycle, signer role and key validation, canonicalization. Flag actual ambiguous/impossible behavior. Owner permission is separate from acceptance (IN_PROGRESS with acceptance NONE is correct, not a defect). Do not claim all legal requirements satisfied. Source input below with line breaks preserved.\n'''+game[start:start+6000]
jobs={'runner':(header+runner,'read_file'),'fixture':(header+fixture,'read_file'),'profile-review':(review,'read_file')}
rows=[]
for name,(task,allowed) in jobs.items():
    attempt=batch/name;work=attempt/'workspace';work.mkdir(parents=True)
    config={'id':'hh3d-bundle-'+name,'attempt':stamp,'session':str(uuid.uuid4()),'workspace':str(work),'notification_repo':str(HERE.parents[3].parent/'hoan-hao'),'turn_limit':6,'max_seconds':420,'notify':True,'web_search':False,'delivery':'JSON_BUNDLE','tools':allowed}
    (attempt/'config.json').write_text(json.dumps(config,indent=2)+'\n',encoding='utf-8')
    (attempt/'TASK.txt').write_text(task,encoding='utf-8')
    shutil.copy2(HERE/'Run-Worker.ps1',attempt/'Run-Worker.ps1')
    rows.append({'role':name,'attempt_dir':str(attempt),'workspace':str(work),'supervisor_pid':None,'session':config['session'],'task_sha256':hashlib.sha256(task.encode()).hexdigest()})
record={'schema':'HH3D-WORKER-BATCH-1','created_utc':stamp,'batch_root':str(batch),'model':'grok-4.6','reasoning_effort':'xhigh','poll_budget':2,'polls_used':0,'jobs':rows}
(HERE/'active-batch.local.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8')
(batch/'batch.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8')
print(str(batch))
